services:
  - type: web
    name: meetup-tracker-api
    env: python
    plan: free
    buildCommand: pip install -r requirements-backend.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: ADMIN_TOKEN
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
