ADMIN_TOKEN = "dev_admin_token_256_char_string_placeholder_for_testing_1234567890abcdef"
APP_PASSWORD = "dev_app_password_512_char_string_placeholder_for_testing_1234567890abcdef"
SMTP_EMAIL = "your_email@example.com"
SMTP_PASSWORD = "your_app_password"